name: Teste
on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Install cal and Lua
      run: sudo apt-get install -y ncal lua5.4
    - name: Clonar site
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'apstaiobeiras'
        repository: 'apstaiobeiras.github.io'

    - name: Clonar base
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'apstaiobeiras'
        repository: 'B'

    - name: Salvar bases e gerar os scripts 
      run: |
        cd B
        #bash baixar-bases.sh
        cd relatorios
        ls
        git config --global user.email "apstaiobeiras@gmail.com"
        git config --global user.name "Bot"
        git add .
        git commit -m "Atualização $(date +'%d/%m/%Y')" || true
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/apstaiobeiras/b.git || true
        git push || true

    - name: Publicar
      run: |
        cd apstaiobeiras.github.io
        git config --global user.email "apstaiobeiras@gmail.com"
        git config --global user.name "Bot"
        git add .
        git commit -m "Atualização $(date +'%d/%m/%Y')"
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/apstaiobeiras/b.git
        git push


